
version: '3'
services:
  mysql:
    build: .
    container_name: mysql_library
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
    